# Header
nav:
  文章: /archives
  分类: /categories
  标签: /tags
  考据相关: /about

# favicon
favicon: /images/portrait.jpeg

# logo
logo: /images/portrait.jpeg

# links
links:
  Github: https://github.com/waser1999
  # ZhiHu:
  Twitter: https://twitter.com/waser1999
  # Weibo: https://weibo.com/u/7096725137

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: false

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable: true
  repo:
  repo_id:
  category:
  category_id:
  mapping:

# maple
maple:
  enable: false
  # fall leaf count
  count: 10
  # 0-1
  speed: 0.5

